// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK-YZFLOSbYdNrnEsivubluxidKfJrdA8',
    appId: '1:1073445060111:web:5b0fd053ab058ff56c2d7a',
    messagingSenderId: '1073445060111',
    projectId: 'smart-call-app',
    authDomain: 'smart-call-app.firebaseapp.com',
    storageBucket: 'smart-call-app.appspot.com',
    measurementId: 'G-XKD3RKF8Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF_ubAPpatV4qlLNEdzOAmI6hc6kQtTNM',
    appId: '1:1073445060111:android:010398215e06116d6c2d7a',
    messagingSenderId: '1073445060111',
    projectId: 'smart-call-app',
    storageBucket: 'smart-call-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKgENNkuNuXRD0irhz-KknOQfm6M25p98',
    appId: '1:1073445060111:ios:c6a1bc1ab85e21546c2d7a',
    messagingSenderId: '1073445060111',
    projectId: 'smart-call-app',
    storageBucket: 'smart-call-app.appspot.com',
    androidClientId: '1073445060111-3snn2qkj7l7l2lk1tbiovdfsencfcm6l.apps.googleusercontent.com',
    iosClientId: '1073445060111-2t2rp01qmh0eaqssk44kg7d77s4tmm03.apps.googleusercontent.com',
    iosBundleId: 'com.hk.smartCallApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKgENNkuNuXRD0irhz-KknOQfm6M25p98',
    appId: '1:1073445060111:ios:c6a1bc1ab85e21546c2d7a',
    messagingSenderId: '1073445060111',
    projectId: 'smart-call-app',
    storageBucket: 'smart-call-app.appspot.com',
    androidClientId: '1073445060111-3snn2qkj7l7l2lk1tbiovdfsencfcm6l.apps.googleusercontent.com',
    iosClientId: '1073445060111-2t2rp01qmh0eaqssk44kg7d77s4tmm03.apps.googleusercontent.com',
    iosBundleId: 'com.hk.smartCallApp',
  );
}
